
      PROGRAM VITGEN_159

************************************************************************
*       tables for interpolation in T of nuclear reaction rates        *
************************************************************************

      implicit none

      integer i,j,k,nreac,nre,ngrid,ngrid1,nvit,nj
      integer iinf,isup,ii,icode,ireac,coef,fs,nbz
      integer n12,n23,n34,nmax,nprint,im,i1,i2,nsp,nsave,echem

      double precision t9min,t9max,dt9,t9,tgrid,flag,ln10
      double precision v,vrate,tnuc9,lnS,t,S,q1,q2
      double precision dt8,t8,t8grid
      double precision t1,t2,t3,t4,dt12,dt23,dt34
      double precision anuc,znuc,zcharge,mass,itype,qinu

      character species*5,cc*40,filename*40,fileout*40,cseq*3,creac*5,
     &     ciso*1,ca*5
      double precision t9l,del

c..   maximum Z (heavy and captn not included)
      parameter (nbz = 28)

      parameter(nreac = 500, nvit = 90)
c      parameter(nre = 180, nvit = 250)

      dimension v(nreac),flag(nreac)
      dimension tnuc9(nvit),vrate(nvit,nreac)
      dimension t8grid(nvit)
      dimension species(100),icode(100),anuc(100),znuc(100),creac(4),
     &     ireac(4),coef(4),itype(4),ciso(2),echem(30,60)


      do i = 1,30
         do j = 1,60
            echem(i,j) = 0
         enddo
      enddo

      ln10 = log(10.d0)
      write (*,*)
      write (*,*) ' Name of input file (generated by NETGEN)'
      write (*,*) ' output : vitsub_159.f'

      read (*,11) cc
 11   format(a40)
      filename = trim(cc)

      open (unit = 20,file = filename)

      open (unit = 99,file = 'starevol.par')
      read(99,40)
 40   format(32/)

      nsp = 0

 41   nsp = nsp+1
      read(99,111) icode(nsp),species(nsp),anuc(nsp),znuc(nsp)
      echem(int(znuc(nsp)),int(anuc(nsp))) =  icode(nsp)
 111  format(i4,1x,a5,1x,f9.5,1x,f4.0)
      if (icode(nsp).lt.icode(nsp-1)) goto 43
      goto 41

 43   species(nsp) = 'NUTRI'
      icode(nsp) = 0
      anuc(nsp) = 0.d0
      znuc(nsp) = 0.d0
      nsp = nsp+1
      species(nsp) = 'BETAP'
      icode(nsp) = 0
      anuc(nsp) = 0.d0
      znuc(nsp) = 1.d0
      nsp = nsp+1
      species(nsp) = 'BETAM'
      icode(nsp) = 0
      anuc(nsp) = 0.d0
      znuc(nsp) = -1.d0
      nsave = 0
      close(99)

      open (unit = 25,file = 'starevolnuc_out.par')
      open (unit=88,file='vit_temp.f')

      ngrid = nvit
c      read (20,100)
      read(20,30)
 30   format((1x,/))
      read (20,55) (t8grid(k),k=1,ngrid)
 55   format(15(/,6(1pe12.6,1x)))
c      print *,t8grid
      write (*,*)
      write (*,*) 'number    flag                     reac'
      write (*,*)
      do k = 1,nreac
         read (20,200,end=25) coef(1),creac(1),ciso(1),coef(2),creac(2)
     &     ,coef(3),creac(3),coef(4),creac(4),ciso(2),q1,q2
 200     format (9x,i1,1x,a5,a1,2x,i1,1x,a5,2x,i1,1x,a5,3x,i1,1x,a5,a1,
     &        7x,f7.3,10x,f7.3,/)
         print *,k,q2
         read (20,300) flag(k)
         if (ciso(1).ne.' ') then
            ca = creac(1)
            creac(1) = ca(1:2) // ca(4:5) // ciso(1)
            print *,'qqq',k,creac(1)
         endif
         if (ciso(2).ne.' ') then
            ca = creac(4)
            creac(4) = ca(1:2) // ca(4:5) // ciso(2)
            print *,'zzz',k,creac(1)
         endif
c         write (*,30) k,flag(k),cc,q1+q2
         if (flag(k).gt.0) stop 'flag'
         qinu = q2

c..   write starevolnuc.out

         do 350 i=1,4
            ireac(i) = -1
            do j=1,nsp
               if (creac(i).eq.species(j)) then
                  ireac(i) = icode(j)
                  itype(i) = j
                  goto 350
               endif
            enddo            
 350     continue         
         fs = int(coef(1)*znuc(itype(1))+dble(nbz)*coef(2)*
     &        (znuc(itype(2))-1))
         if (coef(1).eq.2.and.coef(2).eq.0) then         
            fs = int(znuc(itype(1))+nbz*int(znuc(itype(1))-1.d0))
         endif
         if (znuc(itype(1)).eq.6.d0.and.coef(1).eq.2) fs = 2*nbz+1
         if (znuc(itype(1)).eq.8.d0.and.coef(1).eq.2) fs = 2*nbz+2
         if (coef(2).eq.0.and.coef(1).eq.1) then
            write (88,480) coef(1),creac(1),coef(2),creac(2),coef(3),
     &           creac(3),coef(4),creac(4)
         else
            if (itype(2).eq.1) then
               write (88,486) coef(1),creac(1),coef(2),creac(2),coef(3),
     &              creac(3),coef(4),creac(4),k,k
            else
               if (coef(1).eq.3) fs = -99
               write (88,485) coef(1),creac(1),coef(2),creac(2),coef(3),
     &              creac(3),coef(4),creac(4),k,k,fs
            endif
         endif
 480     format('***',3x,i1,1x,a5,' ( ',i1,1x,a5,', ',i1,1x,a5,')  ',
     &        i1,1x,a5,/)
 485     format('***',3x,i1,1x,a5,' ( ',i1,1x,a5,', ',i1,1x,a5,')  ',i1,
     &        1x,a5,/,6x,'v(',i3,') = v(',i3,')*rok*fscr(ksh,',i3,')')
 486     format('***',3x,i1,1x,a5,' ( ',i1,1x,a5,', ',i1,1x,a5,')  ',
     &        i1,1x,a5,/,6x,'v(',i3,') = v(',i3,')*rok')
         if (k.gt.nsave) then
            zcharge = coef(1)*znuc(itype(1))+coef(2)*znuc(itype(2))
     &           -coef(3)*znuc(itype(3))-coef(4)*znuc(itype(4))
            mass = coef(1)*anuc(itype(1))+coef(2)*anuc(itype(2))-coef(3)
     &           *anuc(itype(3))-coef(4)*anuc(itype(4))
c..   test mass, charge conservation, qinu
c     if ((zcharge.ne.0.d0.or.mass.ne.0.d0).and.qinu.eq.0.d0) 
c     c         if ((zcharge.ne.0.d0.or.mass.ne.0.d0)) 
c     &        write(*,700) k,ireac(1),ireac(2),ireac(3),ireac(4)
c     &        ,int(mass),int(zcharge),species(itype(2)),species(itype(3)
c     &        ),qinu
c            write(*,500) ireac(1),ireac(2),ireac(3),ireac(4)
c 500        format(4(i4))
 700        format(i4,6(1x,i3),3x,a5,',',a5,f7.3)
            nsave = k
         endif
         write (25,444) k,coef(1),creac(1),coef(2),creac(2)
     &     ,coef(3),creac(3),coef(4),creac(4),q1+qinu,ireac(1),
     &        ireac(2),ireac(3),ireac(4),qinu
 444     format(i4,4x,i1,1x,a5,1x,'(',1x,i1,1x,a5,',',1x,i1,1x,a5,1x,
     &        ')',1x,i1,1x,a5,' : Q =',f8.3,' MeV',i7,i4,i4,i4,
     &        '  QINU =',f7.3,' MeV')
         read (20,*) (vrate(j,k), j = 1,ngrid)
      enddo

 25   nre = k
      write (*,21) nre
 21   format(' output : vitsub_',i3,'.f')
      write (cseq,22) nre
 22   format(i3)
      fileout = 'vitsub_' // cseq // '.f'
      open (unit = 10,file = trim(fileout))
c 100  format (44(1x,/))
c 100  format (36(1x,/))
c 30   format(i5,4x,0pf7.2,2x,a39,2x,'Q = ',0pf6.3)
 100  format (17(1x,/))
 300  format (1x,f13.3)
      
c       t8grid(1) = 1.d-2
c       t1 = 1.d-2
c       t2 = 1.d0
c       t3 = 1.d1
c       t4 = 1.d2
c       n12 = 20
c       n23 = 35
c       n34 = 35
c       nmax = n12+n23+n34
c       nprint = int(nmax/5)
c       dt12 = (t2-t1)/dble(n12)
c       dt23 = (t3-t2)/dble(n23)
c       dt34 = (t4-t3)/dble(n34-1)
c       t8grid(nmax) = 5.d1
c c      dt8 = (log10(t8grid(nvit))-log10(t8grid(1)))/(nvit-1)
c c      t8 = log10(t8grid(1))
c       do k = 2,n12+1
c          t8grid(k) = t8grid(k-1)+dt12
c       enddo
c       do k = n12+2,n12+n23+1
c          t8grid(k) = t8grid(k-1)+dt23
c       enddo
c       do k = n12+n23+2,nmax
c          t8grid(k) = t8grid(k-1)+dt34
c       enddo

      do k=1,ngrid
         tnuc9(k) = t8grid(k)*1.d-1
      enddo

      write (10,1000)
      write (10,1200)
      write (10,1000)
      write (10,1100)
      write (10,1300)
      write (10,1100)
      write (10,1000)
      write (10,1400) nvit,nre
      write (10,1500)

      write (10,1501)
      do ii = 1,17
         iinf = 5*ii-4
         isup = iinf+4
         write (10,1502) (tnuc9(i),i = iinf,isup)
      enddo      
      iinf = 5*ii-4
      isup = iinf+4
      write (10,1503) (tnuc9(i),i = iinf,isup)
      write (10,1000)

c S is the conversion factor: sig(mbarn)->Na<sig v>
c      S=7.7629d+04*dsqrt(t8grid(k))

      do i = 1,ngrid
         t = tnuc9(i)*1.d9
         S = 7.7629d+04*dsqrt(10.d0*tnuc9(i))
         do k = 1,nre-1
            if (flag(k).eq.0..or.flag(k).eq.-12.) 
     &           v(k) = log10(vrate(i,k))
            if (flag(k).eq.-1.) v(k) = log10(S*vrate(i,k))
            if (flag(k).eq.-10..or.flag(k).eq.-100.or.flag(k).eq.-14.
     &           .or.flag(k).eq.-11.) v(k) = vrate(i,k)
            if (v(k).lt.-99.d0) v(k) = -99.d0
         enddo         
c neutron sink
c         v(nre) = 13.60745264d0     !ln
         v(nre) = 5.90964159432d0   !ln10
         write (10,1600) t
         write (10,1700) i,i
         im = int(nre/7)
         do k = 1,im
            i1 = (k-1)*7+1
            i2 = i1+6
            write (10,1800) (v(j),j = i1,i2)
         enddo
         k = nre-i2
         if (k.eq.1) write (10,1901) (v(j),j = i2+1,nre)
         if (k.eq.2) write (10,1902) (v(j),j = i2+1,nre)
         if (k.eq.3) write (10,1903) (v(j),j = i2+1,nre)
         if (k.eq.4) write (10,1904) (v(j),j = i2+1,nre)
         if (k.eq.5) write (10,1905) (v(j),j = i2+1,nre)
         if (k.eq.6) write (10,1906) (v(j),j = i2+1,nre)
c         write (10,1904) (v(j),j = 197,197)
      enddo
      write (10,1000)
      write (10,2000)
      write (10,1000)

      close (10)
      close (20)

 1000 format (1x)
 1100 format (72('*'))
 1200 format (6x,'BLOCK DATA VITSUB')
 1300 format ('*',11x,'tables of nuclear reaction rates in ',
     &     'function of T',10x,'*',/,'*',17x,'(see starevol.par for ',
     &     'the references)',16x,'*')
 1400 format (6x,'implicit none',//,
     &     6x,'integer i,j',/,6x,'integer nvit,nre',/,
     &     6x,'double precision tnuc9,vrate',//,
     &     6x,'parameter (nvit = ',i3,', nre = ',i3,')')
 1500 format (6x,'common /nucvit/ tnuc9(nvit),vrate(nvit,nre)')
 1501 format (1x,/,6x,'data (tnuc9(i),i = 1,nvit) /')
 1502 format (5x,'& ',5(1pd12.6,','))
 1503 format (5x,'& ',4(1pd12.6,','),1pd12.6,'/')
 1600 format (1x,/,'***** nav * <sig*v> / rho  at T = ',d10.4,' K')
 1700 format (6x,'data ((vrate(i,j),i = ',i3,',',i3,'),j = 1,nre) /')
 1800 format (5x,'& ',7(f8.4,','))
 1901 format (5x,'& ',f8.4,' /')
 1902 format (5x,'& ',(f8.4,','),f8.4,' /')
 1903 format (5x,'& ',2(f8.4,','),f8.4,' /')
 1904 format (5x,'& ',3(f8.4,','),f8.4,' /')
 1905 format (5x,'& ',4(f8.4,','),f8.4,' /')
 1906 format (5x,'& ',5(f8.4,','),f8.4,' /')
 2000 format (6x,'end',/)

      end

